### ISSUE TITLE
why got phoneme inputs in S2?

### ISSUE THREAD

**Issue by MisakaMikoto96** [innnky/gpt-vits#1]
Hi, thanks for your work! But I am a bit confused that:

Seems like S1 has done the work to get phoneme to semantic token, and do semantic to wav in S2 stage.
Hubwer token has semantic information enough, so why we put phoneme seq in s2?

**Comment by innnky** [comment]
Because the quantization has lost too much information, it is hard for vits to reconstruct the wav. Therefore, phonemes are injected to supplement some of the information lost by quantization.

**Comment by MisakaMikoto96** [comment]
> Because the quantization has lost too much information, it is hard for vits to reconstruct the wav. Therefore, phonemes are injected to supplement some of the information lost by quantization.

so the phonemes in s2 must be similar to those in S1 input right?
